const STORAGE_KEYS={players:"triviaLadder.players.v6",activePlayer:"triviaLadder.activePlayer.v6",results:"triviaLadder.results.v6"};
const QUESTION_VALUES=[100,200,300,400,500],QUESTION_SECONDS=30,FINAL_SECONDS=45;
const DEFAULT_PLAYERS=[{id:"ian",name:"Ian"},{id:"shannon",name:"Shannon"}];
const QUESTION_BANK={
100:[
{id:"100-geography-andes",category:"Geography",difficulty:"Easy",question:"The Andes Mountains are primarily found on which continent?",options:["Europe","South America","Africa","Asia"],answerIndex:1,explanation:"The Andes run along the western side of South America."},
{id:"100-science-water",category:"Science",difficulty:"Easy",question:"What is the chemical formula for water?",options:["CO2","H2O","NaCl","O2"],answerIndex:1,explanation:"Water is made of two hydrogen atoms and one oxygen atom, written as H2O."},
{id:"100-history-egypt",category:"History",difficulty:"Easy",question:"The ancient pyramids of Giza are located in which country?",options:["Greece","Egypt","Turkey","Morocco"],answerIndex:1,explanation:"The pyramids of Giza are located near Cairo, Egypt."},
{id:"100-books-hobbit",category:"Books",difficulty:"Easy",question:"Bilbo Baggins is the main character in which novel?",options:["The Hobbit","Dune","The Lightning Thief","The Giver"],answerIndex:0,explanation:"Bilbo Baggins is the main character of J.R.R. Tolkien’s The Hobbit."},
{id:"100-sports-wimbledon",category:"Sports",difficulty:"Easy",question:"Wimbledon is a major tournament in which sport?",options:["Golf","Tennis","Cricket","Soccer"],answerIndex:1,explanation:"Wimbledon is one of tennis’s four Grand Slam tournaments."},
{id:"100-movies-oscar",category:"Movies",difficulty:"Easy",question:"What award is given by the Academy of Motion Picture Arts and Sciences?",options:["Grammy","Oscar","Emmy","Tony"],answerIndex:1,explanation:"The Academy Awards are commonly called the Oscars."},
{id:"100-bible-moses",category:"Bible",difficulty:"Easy",question:"Who led the Israelites out of Egypt in the book of Exodus?",options:["David","Moses","Paul","Solomon"],answerIndex:1,explanation:"Moses leads the Israelites out of Egypt in Exodus."},
{id:"100-food-sushi",category:"Food",difficulty:"Easy",question:"Sushi is most strongly associated with which country?",options:["Japan","Spain","Brazil","Egypt"],answerIndex:0,explanation:"Sushi is strongly associated with Japanese cuisine."}
],
200:[
{id:"200-geography-madagascar",category:"Geography",difficulty:"Medium",question:"Madagascar lies off the southeastern coast of which continent?",options:["Asia","Africa","Australia","South America"],answerIndex:1,explanation:"Madagascar is an island country off the southeastern coast of Africa."},
{id:"200-science-carbon",category:"Science",difficulty:"Medium",question:"Which element has the atomic number 6?",options:["Oxygen","Carbon","Nitrogen","Helium"],answerIndex:1,explanation:"Carbon has atomic number 6 on the periodic table."},
{id:"200-history-constantinople",category:"History",difficulty:"Medium",question:"Constantinople is now known as which city?",options:["Athens","Istanbul","Rome","Cairo"],answerIndex:1,explanation:"Constantinople became known as Istanbul."},
{id:"200-literature-atticus",category:"Literature",difficulty:"Medium",question:"Atticus Finch is a central character in which novel?",options:["The Great Gatsby","To Kill a Mockingbird","Of Mice and Men","Fahrenheit 451"],answerIndex:1,explanation:"Atticus Finch is a lawyer and central character in To Kill a Mockingbird."},
{id:"200-sports-tour",category:"Sports",difficulty:"Medium",question:"The yellow jersey is associated with the leader of which race?",options:["Tour de France","Boston Marathon","Kentucky Derby","Indianapolis 500"],answerIndex:0,explanation:"The yellow jersey is worn by the overall leader of the Tour de France."},
{id:"200-music-clef",category:"Music",difficulty:"Medium",question:"Which clef is also known as the G clef?",options:["Bass clef","Treble clef","Alto clef","Tenor clef"],answerIndex:1,explanation:"The treble clef is also called the G clef."},
{id:"200-bible-daniel",category:"Bible",difficulty:"Medium",question:"Which biblical figure interpreted dreams for King Nebuchadnezzar?",options:["Daniel","Jonah","Samuel","Elijah"],answerIndex:0,explanation:"Daniel interprets dreams for King Nebuchadnezzar in the Book of Daniel."},
{id:"200-tech-html",category:"Technology",difficulty:"Medium",question:"What does HTML stand for?",options:["HyperText Markup Language","High Transfer Machine Logic","Home Tool Markup List","Hyperlink Text Management Layer"],answerIndex:0,explanation:"HTML stands for HyperText Markup Language."}
],
300:[
{id:"300-science-oxygen",category:"Science",difficulty:"Hard",question:"Which scientist is often credited with discovering oxygen independently in the 1770s?",options:["Joseph Priestley","Isaac Newton","Michael Faraday","Gregor Mendel"],answerIndex:0,explanation:"Joseph Priestley is often credited with discovering oxygen independently in the 1770s."},
{id:"300-geography-capital-canada",category:"Geography",difficulty:"Hard",question:"What is the capital city of Canada?",options:["Toronto","Vancouver","Montreal","Ottawa"],answerIndex:3,explanation:"Ottawa is the capital of Canada."},
{id:"300-history-westphalia",category:"History",difficulty:"Hard",question:"The Peace of Westphalia ended which major European conflict?",options:["The Hundred Years’ War","The Thirty Years’ War","The War of Spanish Succession","The Napoleonic Wars"],answerIndex:1,explanation:"The Peace of Westphalia ended the Thirty Years’ War in 1648."},
{id:"300-literature-hamlet",category:"Literature",difficulty:"Hard",question:"Which Shakespeare play is set mainly in Denmark?",options:["Macbeth","Hamlet","Othello","King Lear"],answerIndex:1,explanation:"Hamlet is set mainly in Denmark."},
{id:"300-sports-perfect",category:"Sports",difficulty:"Hard",question:"In baseball, how many batters are retired in a perfect 9-inning game?",options:["24","25","27","30"],answerIndex:2,explanation:"A perfect game requires 27 consecutive outs."},
{id:"300-art-starry",category:"Art",difficulty:"Hard",question:"Who painted The Starry Night?",options:["Claude Monet","Pablo Picasso","Vincent van Gogh","Salvador Dalí"],answerIndex:2,explanation:"Vincent van Gogh painted The Starry Night."},
{id:"300-food-tiramisu",category:"Food",difficulty:"Hard",question:"Which Italian dessert uses mascarpone and espresso-soaked ladyfingers?",options:["Cannoli","Tiramisu","Gelato","Panna cotta"],answerIndex:1,explanation:"Tiramisu is made with mascarpone and coffee-soaked ladyfingers."},
{id:"300-mythology-odysseus",category:"Mythology",difficulty:"Hard",question:"Who is the hero of Homer’s Odyssey?",options:["Achilles","Odysseus","Hector","Perseus"],answerIndex:1,explanation:"The Odyssey follows Odysseus on his journey home."}
],
400:[
{id:"400-science-avogadro",category:"Science",difficulty:"Harder",question:"Avogadro’s number is closest to which value?",options:["3.14 x 10^8","6.02 x 10^23","9.81 x 10^2","1.61 x 10^12"],answerIndex:1,explanation:"Avogadro’s number is approximately 6.02 x 10^23."},
{id:"400-geography-bosporus",category:"Geography",difficulty:"Harder",question:"The Bosporus strait separates which two continents?",options:["Europe and Asia","Africa and Asia","Europe and Africa","North America and South America"],answerIndex:0,explanation:"The Bosporus separates Europe and Asia in Turkey."},
{id:"400-history-meiji",category:"History",difficulty:"Harder",question:"The Meiji Restoration transformed which country in the 19th century?",options:["China","Japan","Korea","Thailand"],answerIndex:1,explanation:"The Meiji Restoration transformed Japan beginning in 1868."},
{id:"400-literature-gatsby",category:"Literature",difficulty:"Harder",question:"What is the name of the narrator in The Great Gatsby?",options:["Jay Gatsby","Tom Buchanan","Nick Carraway","George Wilson"],answerIndex:2,explanation:"Nick Carraway narrates The Great Gatsby."},
{id:"400-sports-cricket",category:"Sports",difficulty:"Harder",question:"In cricket, what is the term for a score of zero by a batter?",options:["Duck","Blank","Nil","Scratch"],answerIndex:0,explanation:"A score of zero in cricket is called a duck."},
{id:"400-music-baroque",category:"Music",difficulty:"Harder",question:"Johann Sebastian Bach is most closely associated with which musical period?",options:["Romantic","Classical","Baroque","Modern"],answerIndex:2,explanation:"Bach is one of the defining composers of the Baroque period."},
{id:"400-bible-damascus",category:"Bible",difficulty:"Harder",question:"Saul’s conversion is traditionally associated with the road to which city?",options:["Jerusalem","Damascus","Rome","Antioch"],answerIndex:1,explanation:"Saul’s conversion is associated with the road to Damascus."},
{id:"400-tech-eniac",category:"Technology",difficulty:"Harder",question:"ENIAC is commonly associated with the early history of what?",options:["Television","Computers","Satellites","Radio"],answerIndex:1,explanation:"ENIAC was an early electronic general-purpose computer."}
],
500:[
{id:"500-science-schrodinger",category:"Science",difficulty:"Very Hard",question:"Schrödinger’s equation is most closely associated with which field?",options:["Quantum mechanics","Plate tectonics","Classical optics","Thermodynamics"],answerIndex:0,explanation:"Schrödinger’s equation is a central equation in quantum mechanics."},
{id:"500-geography-titicaca",category:"Geography",difficulty:"Very Hard",question:"Lake Titicaca lies on the border of Bolivia and which other country?",options:["Chile","Peru","Ecuador","Argentina"],answerIndex:1,explanation:"Lake Titicaca lies on the border of Bolivia and Peru."},
{id:"500-history-magna",category:"History",difficulty:"Very Hard",question:"The Magna Carta was agreed to by King John in which year?",options:["1066","1215","1415","1492"],answerIndex:1,explanation:"King John agreed to the Magna Carta in 1215."},
{id:"500-literature-ulysses",category:"Literature",difficulty:"Very Hard",question:"Who wrote the novel Ulysses?",options:["James Joyce","Virginia Woolf","T.S. Eliot","D.H. Lawrence"],answerIndex:0,explanation:"James Joyce wrote Ulysses."},
{id:"500-art-guernica",category:"Art",difficulty:"Very Hard",question:"Guernica was painted by which artist?",options:["Pablo Picasso","Henri Matisse","Joan Miró","Diego Rivera"],answerIndex:0,explanation:"Pablo Picasso painted Guernica."},
{id:"500-sports-curling",category:"Sports",difficulty:"Very Hard",question:"In curling, what is the target area called?",options:["The house","The pocket","The rink","The circle"],answerIndex:0,explanation:"The target area in curling is called the house."},
{id:"500-music-dvorak",category:"Music",difficulty:"Very Hard",question:"Antonín Dvořák’s Symphony No. 9 is commonly known by what name?",options:["Eroica","From the New World","Pastoral","Jupiter"],answerIndex:1,explanation:"Dvořák’s Symphony No. 9 is commonly called From the New World."},
{id:"500-math-euler",category:"Math",difficulty:"Very Hard",question:"Euler’s identity includes which mathematical constant represented by the letter e?",options:["The golden ratio","The base of natural logarithms","The imaginary unit","The speed of light"],answerIndex:1,explanation:"In Euler’s identity, e is the base of natural logarithms."}
]
};
const FINAL_BANK=[
{id:"final-science-nitrogen",category:"Science",question:"Which element makes up the largest share of Earth’s atmosphere?",options:["Oxygen","Nitrogen","Argon","Carbon dioxide"],answerIndex:1,explanation:"Nitrogen makes up the largest share of Earth’s atmosphere."},
{id:"final-history-adams",category:"U.S. History",question:"Who was the first U.S. president to live in the White House?",options:["George Washington","John Adams","Thomas Jefferson","James Madison"],answerIndex:1,explanation:"John Adams was the first president to live in the White House."},
{id:"final-geography-africa",category:"World Geography",question:"Which continent has the most countries?",options:["Africa","Asia","Europe","South America"],answerIndex:0,explanation:"Africa has the most internationally recognized countries of any continent."},
{id:"final-literature-smaug",category:"Books",question:"In The Hobbit, what is the name of the dragon?",options:["Smaug","Glaurung","Drogon","Ancalagon"],answerIndex:0,explanation:"Smaug is the dragon in The Hobbit."},
{id:"final-sports-mound",category:"Sports",question:"In Major League Baseball, the pitching rubber is how far from home plate?",options:["55 feet","60 feet 6 inches","63 feet","66 feet 6 inches"],answerIndex:1,explanation:"The MLB pitching rubber is 60 feet 6 inches from home plate."},
{id:"final-music-abbey",category:"Music",question:"Which Beatles album features the song Come Together?",options:["Revolver","Abbey Road","Rubber Soul","Let It Be"],answerIndex:1,explanation:"Come Together appears on Abbey Road."}
];
const state={players:[],activePlayerId:null,results:{},game:null,timerId:null};
const app=document.getElementById("app"),toast=document.getElementById("toast");
function init(){state.players=loadJSON(STORAGE_KEYS.players,DEFAULT_PLAYERS);state.activePlayerId=localStorage.getItem(STORAGE_KEYS.activePlayer)||"ian";state.results=loadJSON(STORAGE_KEYS.results,{});for(const p of DEFAULT_PLAYERS){if(!state.players.some(x=>x.id===p.id))state.players.push(p)}if(!state.players.some(p=>p.id===state.activePlayerId))state.activePlayerId=state.players[0]?.id||"ian";persistPlayers();renderHome()}
function cloneFallback(x){return JSON.parse(JSON.stringify(x))}
function loadJSON(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):cloneFallback(f)}catch{return cloneFallback(f)}}
function saveJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}function persistPlayers(){saveJSON(STORAGE_KEYS.players,state.players);localStorage.setItem(STORAGE_KEYS.activePlayer,state.activePlayerId)}function persistResults(){saveJSON(STORAGE_KEYS.results,state.results)}
function activePlayer(){return state.players.find(p=>p.id===state.activePlayerId)}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function formatDateLabel(k){const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}
function money(v){return `$${Number(v||0).toLocaleString()}`}
function hashString(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)}
function pickDailyQuestion(value,dateKey,usedCategories){
  const bank=QUESTION_BANK[value]||[];
  const seed=hashString(`${dateKey}-${value}-difficulty-ladder-v6`);
  const shuffled=[...bank].sort((a,b)=>{
    const ah=hashString(`${dateKey}-${value}-${a.id}`),bh=hashString(`${dateKey}-${value}-${b.id}`);
    return ah-bh;
  });
  const preferred=shuffled.find(q=>!usedCategories.has(q.category))||shuffled[seed%shuffled.length];
  usedCategories.add(preferred.category);
  return{...preferred,value};
}
function dailySet(dateKey=todayKey()){
  const usedCategories=new Set();
  return{
    dateKey,
    questions:QUESTION_VALUES.map(value=>pickDailyQuestion(value,dateKey,usedCategories)),
    final:(()=>{const idx=hashString(`${dateKey}-final-ladder-v6`)%FINAL_BANK.length;return FINAL_BANK[idx]})()
  }
}
function playerResult(dateKey,playerId){return state.results?.[dateKey]?.[playerId]||null}
function renderHome(){clearTimer();state.game=null;const existing=playerResult(todayKey(),state.activePlayerId);app.innerHTML=`<section class="screen"><div class="card home-card"><div class="logo">$</div><span class="eyebrow">${formatDateLabel(todayKey())}</span><h1>Today’s Board Is Live</h1><p class="subtext">Choose player, start today’s round, and see who owns the board.</p><div class="player-picker">${state.players.map(p=>`<button class="player-option ${p.id===state.activePlayerId?"active":""}" data-player-id="${p.id}" type="button">${escapeHTML(p.name)}</button>`).join("")}</div><div class="home-actions"><button class="primary-btn" id="startRoundButton" type="button">${existing?"View Today’s Result":"Start Today’s Round"}</button><button class="secondary-btn" id="leaderboardButton" type="button">Leaderboard</button></div></div></section>`;document.querySelectorAll(".player-option").forEach(b=>b.addEventListener("click",()=>{state.activePlayerId=b.dataset.playerId;persistPlayers();renderHome()}));document.getElementById("startRoundButton").addEventListener("click",()=>{const r=playerResult(todayKey(),state.activePlayerId);r?renderResults(r):startGame()});document.getElementById("leaderboardButton").addEventListener("click",renderLeaderboard)}
function startGame(){const set=dailySet(),p=activePlayer();if(!p)return renderHome();const existing=playerResult(set.dateKey,p.id);if(existing)return renderResults(existing);state.game={playerId:p.id,playerName:p.name,dateKey:set.dateKey,questions:set.questions,final:set.final,currentIndex:0,bank:0,answers:[],selectedIndex:null,phase:"question",locked:false,completed:false,timeLeft:QUESTION_SECONDS};renderQuestion()}
function renderQuestion(){clearTimer();const g=state.game,q=g.questions[g.currentIndex];g.selectedIndex=null;g.locked=false;g.phase="question";g.timeLeft=QUESTION_SECONDS;app.innerHTML=`<section class="screen"><div class="game-header"><div class="header-left"><span class="round-label">Q${g.currentIndex+1} · ${escapeHTML(q.category)} · ${escapeHTML(q.difficulty||"")} · ${money(q.value)}</span><span class="bank-label">${escapeHTML(g.playerName)} · Bank ${money(g.bank)}</span></div><div class="timer" id="timer">${g.timeLeft}</div></div><div class="card game-card"><span class="clue-value">For ${money(q.value)}</span><div class="clue-text">${escapeHTML(q.question)}</div><div class="answer-grid">${q.options.map((o,i)=>`<button class="answer-option" data-answer-index="${i}" type="button">${escapeHTML(o)}</button>`).join("")}</div><div class="submit-area"><button class="primary-btn" id="submitAnswerButton" type="button" disabled>Submit</button></div></div></section>`;document.querySelectorAll(".answer-option").forEach(b=>b.addEventListener("click",()=>{if(g.locked)return;g.selectedIndex=Number(b.dataset.answerIndex);document.querySelectorAll(".answer-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.getElementById("submitAnswerButton").disabled=false}));document.getElementById("submitAnswerButton").addEventListener("click",()=>submitQuestionAnswer(g.selectedIndex,"answer"));startTimer(()=>submitQuestionAnswer(null,"time"))}
function submitQuestionAnswer(selectedIndex,reason="answer"){const g=state.game;if(!g||g.locked)return;g.locked=true;clearTimer();const q=g.questions[g.currentIndex],correct=selectedIndex===q.answerIndex,earned=correct?q.value:0;g.bank+=earned;const answer={questionId:q.id,category:q.category,value:q.value,selectedIndex,correct,earned,reason};g.answers.push(answer);renderQuestionFeedback(q,answer)}
function renderQuestionFeedback(q,a){const g=state.game,isLast=g.currentIndex+1>=g.questions.length,title=a.correct?"Correct!":a.reason==="time"?"Time!":a.reason==="tab"?"Forfeit!":"Incorrect",subtitle=a.correct?`You won ${money(a.earned)}.`:"You won $0.";app.innerHTML=`<section class="screen"><div class="game-header"><div class="header-left"><span class="round-label">Q${g.currentIndex+1} Result</span><span class="bank-label">Current Bank ${money(g.bank)}</span></div></div><div class="card game-card"><div class="feedback-card"><span class="feedback-title ${a.correct?"good":"bad"}">${title}</span><span class="feedback-money">${subtitle}</span><p class="feedback-explanation">${escapeHTML(q.explanation)}</p><button class="primary-btn" id="nextButton" type="button">${isLast?"Go to Final Ladder":"Next Clue"}</button></div></div></section>`;document.getElementById("nextButton").addEventListener("click",()=>{if(isLast)renderFinalSetup();else{g.currentIndex+=1;renderQuestion()}})}
function renderFinalSetup(){clearTimer();const g=state.game;app.innerHTML=`<section class="screen"><div class="card final-card"><span class="eyebrow">Final Ladder</span><h2>Make Your Wager</h2><p class="subtext">Current Bank: ${money(g.bank)}. Correct adds your wager. Incorrect subtracts it.</p><div class="wager-options"><input class="text-input" id="wagerInput" type="number" min="0" max="${g.bank}" step="100" value="${Math.min(500,g.bank)}"/><div class="row-actions"><button class="secondary-btn" data-wager="0" type="button">${money(0)}</button><button class="secondary-btn" data-wager="${Math.floor(g.bank/2)}" type="button">Half</button><button class="secondary-btn" data-wager="${g.bank}" type="button">All In</button></div></div><div class="row-actions"><button class="primary-btn" id="lockWagerButton" type="button">Lock Wager</button><button class="secondary-btn" id="skipFinalButton" type="button">Skip Final</button></div></div></section>`;document.querySelectorAll("[data-wager]").forEach(b=>b.addEventListener("click",()=>document.getElementById("wagerInput").value=b.dataset.wager));document.getElementById("lockWagerButton").addEventListener("click",()=>{g.finalWager=clampWager(Number(document.getElementById("wagerInput").value||0),g.bank);renderFinalQuestion()});document.getElementById("skipFinalButton").addEventListener("click",()=>saveCompletedGame({selectedIndex:null,correct:false,wager:0,reason:"skipped",earned:0}))}
function renderFinalQuestion(){clearTimer();const g=state.game,f=g.final;g.selectedIndex=null;g.locked=false;g.phase="final";g.timeLeft=FINAL_SECONDS;app.innerHTML=`<section class="screen"><div class="game-header"><div class="header-left"><span class="round-label">Final Ladder · ${escapeHTML(f.category)}</span><span class="bank-label">Bank ${money(g.bank)} · Wager ${money(g.finalWager)}</span></div><div class="timer" id="timer">${g.timeLeft}</div></div><div class="card game-card"><span class="clue-value">Final Wager ${money(g.finalWager)}</span><div class="clue-text">${escapeHTML(f.question)}</div><div class="answer-grid">${f.options.map((o,i)=>`<button class="answer-option" data-answer-index="${i}" type="button">${escapeHTML(o)}</button>`).join("")}</div><div class="submit-area"><button class="primary-btn" id="submitFinalButton" type="button" disabled>Submit Final</button></div></div></section>`;document.querySelectorAll(".answer-option").forEach(b=>b.addEventListener("click",()=>{if(g.locked)return;g.selectedIndex=Number(b.dataset.answerIndex);document.querySelectorAll(".answer-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.getElementById("submitFinalButton").disabled=false}));document.getElementById("submitFinalButton").addEventListener("click",()=>submitFinalAnswer(g.selectedIndex,"answer"));startTimer(()=>submitFinalAnswer(null,"time"))}
function submitFinalAnswer(selectedIndex,reason="answer"){const g=state.game;if(!g||g.locked)return;g.locked=true;clearTimer();const f=g.final,correct=selectedIndex===f.answerIndex,earned=correct?g.finalWager:-g.finalWager,finalBank=Math.max(0,g.bank+earned);renderFinalFeedback(f,{selectedIndex,correct,wager:g.finalWager,reason,earned,finalBank})}
function renderFinalFeedback(f,a){const title=a.correct?"Correct!":a.reason==="time"?"Time!":a.reason==="tab"?"Forfeit!":"Incorrect",moneyText=a.correct?`You added ${money(a.wager)}.`:`You lost ${money(a.wager)}.`;app.innerHTML=`<section class="screen"><div class="card game-card"><div class="feedback-card"><span class="feedback-title ${a.correct?"good":"bad"}">${title}</span><span class="feedback-money">${moneyText}</span><p class="feedback-explanation">${escapeHTML(f.explanation)}</p><button class="primary-btn" id="saveResultButton" type="button">Save Result</button></div></div></section>`;document.getElementById("saveResultButton").addEventListener("click",()=>saveCompletedGame(a))}
function saveCompletedGame(finalAnswer){const g=state.game,bank=typeof finalAnswer.finalBank==="number"?finalAnswer.finalBank:Math.max(0,g.bank+(finalAnswer.earned||0));const result={playerId:g.playerId,playerName:g.playerName,dateKey:g.dateKey,bank,completedAt:new Date().toISOString(),answers:g.answers,final:{questionId:g.final.id,category:g.final.category,wager:finalAnswer.wager||0,selectedIndex:finalAnswer.selectedIndex,correct:finalAnswer.correct,reason:finalAnswer.reason,earned:finalAnswer.earned||0}};if(!state.results[g.dateKey])state.results[g.dateKey]={};state.results[g.dateKey][g.playerId]=result;persistResults();state.game=null;showToast("Result saved.");renderResults(result)}
function renderResults(result){clearTimer();const stats=computeStats(),s=stats[result.playerId]||{record:{w:0,d:0,l:0},streak:"—",lifetimeBank:result.bank};app.innerHTML=`<section class="screen"><div class="card results-card"><span class="eyebrow">${formatDateLabel(result.dateKey)}</span><h2>${escapeHTML(result.playerName)}’s Final Bank</h2><div class="big-money">${money(result.bank)}</div><div class="stat-grid"><div class="stat-card"><span>Overall Record</span><strong>${s.record.w}-${s.record.d}-${s.record.l}</strong></div><div class="stat-card"><span>Current Streak</span><strong>${s.streak}</strong></div><div class="stat-card"><span>Lifetime Bank</span><strong>${money(s.lifetimeBank)}</strong></div></div><div class="share-card"><h3>Playing on separate phones?</h3><p class="small-muted">Copy this score code and text it over. The other phone can import it on the leaderboard.</p><textarea class="score-code" id="scoreCodeBox" readonly>${encodeScoreCode(result)}</textarea><button class="primary-btn" id="copyScoreCodeButton" type="button">Copy Score Code</button></div><div class="row-actions"><button class="primary-btn" id="leaderboardButton" type="button">Leaderboard</button><button class="secondary-btn" id="homeButton" type="button">Home</button><button class="danger-btn" id="resetTodayButton" type="button">Reset Today</button></div></div></section>`;document.getElementById("copyScoreCodeButton").addEventListener("click",async()=>{await copyTextToClipboard(document.getElementById("scoreCodeBox").value);showToast("Score code copied.")});document.getElementById("leaderboardButton").addEventListener("click",renderLeaderboard);document.getElementById("homeButton").addEventListener("click",renderHome);document.getElementById("resetTodayButton").addEventListener("click",()=>{if(state.results[todayKey()]?.[result.playerId]){delete state.results[todayKey()][result.playerId];persistResults();showToast("Today’s score reset.");renderHome()}})}
function renderLeaderboard(){clearTimer();const stats=computeStats(),sorted=Object.values(stats).sort((a,b)=>{const t=(b.todayBank??-1)-(a.todayBank??-1);return t!==0?t:b.lifetimeBank-a.lifetimeBank});const rows=sorted.map(s=>`<tr><td><strong>${escapeHTML(s.player.name)}</strong></td><td class="money-cell">${s.todayBank===null?"—":money(s.todayBank)}</td><td>${s.record.w}-${s.record.d}-${s.record.l}</td><td>${s.streak}</td><td>${s.winsThisWeek}</td><td>${s.overallWins}</td><td class="money-cell">${money(s.lifetimeBank)}</td></tr>`).join("");app.innerHTML=`<section class="screen"><div class="card leaderboard-card"><span class="eyebrow">${formatDateLabel(todayKey())}</span><h2>Leaderboard</h2><div class="table-wrap"><table><thead><tr><th>Player</th><th>Today</th><th>Record</th><th>Streak</th><th>Week Wins</th><th>Total Wins</th><th>Lifetime</th></tr></thead><tbody>${rows}</tbody></table></div><div class="import-card"><h3>Import Score Code</h3><p class="small-muted">Paste the score code from the other phone to update this leaderboard.</p><textarea class="score-code" id="importScoreCodeBox" placeholder="Paste score code here"></textarea><button class="primary-btn" id="importScoreButton" type="button">Import Score</button></div><div class="row-actions"><button class="primary-btn" id="homeButton" type="button">Home</button><button class="danger-btn" id="clearDataButton" type="button">Clear Saved Data</button></div></div></section>`;document.getElementById("homeButton").addEventListener("click",renderHome);document.getElementById("importScoreButton").addEventListener("click",()=>{const code=document.getElementById("importScoreCodeBox").value.trim();if(!code)return showToast("Paste a score code first.");try{const imported=importScoreCode(code);showToast(`${imported.playerName}'s ${money(imported.bank)} score imported.`);renderLeaderboard()}catch{showToast("That score code did not work.")}});document.getElementById("clearDataButton").addEventListener("click",()=>{if(!window.confirm("Clear all saved scores from this browser?"))return;localStorage.removeItem(STORAGE_KEYS.results);state.results={};showToast("Scores cleared.");renderLeaderboard()})}
function computeStats(){const stats={},playerIds=state.players.map(p=>p.id);for(const player of state.players)stats[player.id]={player,todayBank:playerResult(todayKey(),player.id)?.bank??null,lifetimeBank:0,overallWins:0,winsThisWeek:0,record:{w:0,d:0,l:0},streak:"—"};for(const [dateKey,byPlayer] of Object.entries(state.results||{}))for(const [playerId,result] of Object.entries(byPlayer||{}))if(stats[playerId])stats[playerId].lifetimeBank+=result.bank||0;const dates=Object.keys(state.results||{}).sort(),weekStart=getWeekStart();for(const dateKey of dates){const byPlayer=state.results[dateKey]||{},completed=playerIds.map(id=>({id,result:byPlayer[id]})).filter(x=>x.result);if(completed.length<2)continue;const high=Math.max(...completed.map(x=>x.result.bank)),winners=completed.filter(x=>x.result.bank===high),isThisWeek=keyToDate(dateKey)>=weekStart;for(const item of completed){if(winners.length>1)stats[item.id].record.d+=1;else if(winners[0].id===item.id){stats[item.id].record.w+=1;stats[item.id].overallWins+=1;if(isThisWeek)stats[item.id].winsThisWeek+=1}else stats[item.id].record.l+=1}}for(const id of playerIds)stats[id].streak=computeCurrentStreak(id,dates);return stats}
function computeCurrentStreak(playerId,dates){const playerIds=state.players.map(p=>p.id);let type=null,count=0;for(let i=dates.length-1;i>=0;i--){const byPlayer=state.results[dates[i]]||{},completed=playerIds.map(id=>({id,result:byPlayer[id]})).filter(x=>x.result);if(completed.length<2||!byPlayer[playerId])continue;const high=Math.max(...completed.map(x=>x.result.bank)),winners=completed.filter(x=>x.result.bank===high),dayType=winners.length>1?"D":winners[0].id===playerId?"W":"L";if(!type){type=dayType;count=1}else if(type===dayType)count+=1;else break}return type?`${type}${count}`:"—"}
function getWeekStart(date=new Date()){const d=new Date(date),day=d.getDay(),diff=day===0?-6:1-day;d.setDate(d.getDate()+diff);d.setHours(0,0,0,0);return d}function keyToDate(k){const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d)}
function startTimer(onExpire){clearTimer();state.timerId=setInterval(()=>{if(!state.game||state.game.locked)return;state.game.timeLeft-=1;const timer=document.getElementById("timer");if(timer){timer.textContent=Math.max(state.game.timeLeft,0);timer.classList.toggle("warning",state.game.timeLeft<=10)}if(state.game.timeLeft<=0)onExpire()},1000)}function clearTimer(){if(state.timerId)clearInterval(state.timerId);state.timerId=null}
document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.game&&!state.game.locked){state.game.phase==="final"?submitFinalAnswer(null,"tab"):submitQuestionAnswer(null,"tab")}});
function clampWager(wager,bank){if(!Number.isFinite(wager))return 0;return Math.max(0,Math.min(bank,Math.round(wager)))}
function encodeScoreCode(result){const safe={app:"trivia-ladder",version:6,dateKey:result.dateKey,playerName:result.playerName,bank:result.bank,completedAt:result.completedAt,answers:result.answers||[],final:result.final||{}};return btoa(unescape(encodeURIComponent(JSON.stringify(safe))))}
function decodeScoreCode(code){const json=decodeURIComponent(escape(atob(String(code||"").trim()))),payload=JSON.parse(json);if(payload.app!=="trivia-ladder"||!payload.dateKey||!payload.playerName||typeof payload.bank!=="number")throw new Error("Invalid score code");return payload}
function importScoreCode(code){const payload=decodeScoreCode(code),name=String(payload.playerName||"Player").trim();let player=state.players.find(p=>p.name.toLowerCase()===name.toLowerCase());if(!player){player={id:makeSafePlayerIdFromName(name),name,createdAt:new Date().toISOString(),imported:true};state.players.push(player);persistPlayers()}const result={...payload,playerId:player.id,playerName:player.name,importedAt:new Date().toISOString()};if(!state.results[payload.dateKey])state.results[payload.dateKey]={};state.results[payload.dateKey][player.id]=result;persistResults();return result}
function makeSafePlayerIdFromName(name){const clean=String(name||"Player").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");return clean||`player_${Date.now()}`}async function copyTextToClipboard(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);const ta=document.createElement("textarea");ta.value=text;ta.style.position="fixed";ta.style.left="-9999px";document.body.appendChild(ta);ta.focus();ta.select();document.execCommand("copy");ta.remove()}
function showToast(message){toast.textContent=message;toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),2300)}
function escapeHTML(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
init();
