const STORAGE_KEYS={players:"triviaLadder.players.v4",activePlayer:"triviaLadder.activePlayer.v4",results:"triviaLadder.results.v4"};
const QUESTION_VALUES=[100,200,300,400,500],QUESTION_SECONDS=30,FINAL_SECONDS=45;
const DEFAULT_PLAYERS=[{id:"ian",name:"Ian"},{id:"shannon",name:"Shannon"}];
const QUESTION_BANK={
100:[
{id:"100-science-red-planet",category:"Science",difficulty:"Easy",question:"Which planet is known as the Red Planet?",options:["Venus","Mars","Jupiter","Mercury"],answerIndex:1,explanation:"Mars is called the Red Planet because iron oxide gives its surface a reddish color."},
{id:"100-geography-france",category:"Geography",difficulty:"Easy",question:"What is the capital of France?",options:["Madrid","Rome","Paris","Berlin"],answerIndex:2,explanation:"Paris is the capital of France."},
{id:"100-sports-mlb-innings",category:"Sports",difficulty:"Easy",question:"How many innings are in a standard MLB game?",options:["7","8","9","10"],answerIndex:2,explanation:"A standard Major League Baseball game is scheduled for 9 innings."},
{id:"100-bible-genesis",category:"Bible",difficulty:"Easy",question:"What is the first book of the Bible?",options:["Exodus","Genesis","Matthew","Psalms"],answerIndex:1,explanation:"Genesis is the first book of the Bible."},
{id:"100-movies-toy-story",category:"Movies",difficulty:"Easy",question:"Which movie features Woody and Buzz Lightyear?",options:["Shrek","Toy Story","Cars","Finding Nemo"],answerIndex:1,explanation:"Woody and Buzz Lightyear are main characters in Toy Story."},
{id:"100-food-pizza",category:"Food",difficulty:"Easy",question:"Pizza is most famously associated with which country?",options:["Italy","Mexico","Greece","France"],answerIndex:0,explanation:"Pizza is strongly associated with Italy, especially Naples."},
{id:"100-music-beatles",category:"Music",difficulty:"Easy",question:"Which band was made up of John, Paul, George, and Ringo?",options:["The Rolling Stones","The Beatles","Queen","U2"],answerIndex:1,explanation:"John, Paul, George, and Ringo were The Beatles."},
{id:"100-tv-simpsons",category:"TV",difficulty:"Easy",question:"What color are The Simpsons characters usually shown as?",options:["Blue","Green","Yellow","Purple"],answerIndex:2,explanation:"The Simpsons are famously animated with yellow skin."}
],
200:[
{id:"200-science-heart",category:"Science",difficulty:"Easy-Medium",question:"Which organ pumps blood through the human body?",options:["Lung","Liver","Brain","Heart"],answerIndex:3,explanation:"The heart pumps blood through the circulatory system."},
{id:"200-geography-pacific",category:"Geography",difficulty:"Easy-Medium",question:"What is the largest ocean on Earth?",options:["Atlantic","Indian","Pacific","Arctic"],answerIndex:2,explanation:"The Pacific Ocean is Earth’s largest ocean."},
{id:"200-sports-guardians",category:"Sports",difficulty:"Easy-Medium",question:"The Guardians play Major League Baseball in which city?",options:["Cincinnati","Cleveland","Detroit","Pittsburgh"],answerIndex:1,explanation:"The Cleveland Guardians play in Cleveland, Ohio."},
{id:"200-movies-nemo",category:"Movies",difficulty:"Easy-Medium",question:"In Finding Nemo, what kind of fish is Nemo?",options:["Clownfish","Goldfish","Angelfish","Blue tang"],answerIndex:0,explanation:"Nemo is a clownfish."},
{id:"200-history-liberty-gift",category:"History",difficulty:"Easy-Medium",question:"The Statue of Liberty was a gift from which country?",options:["France","Spain","England","Italy"],answerIndex:0,explanation:"France gave the Statue of Liberty to the United States."},
{id:"200-books-hogwarts",category:"Books",difficulty:"Easy-Medium",question:"What is the name of Harry Potter’s wizarding school?",options:["Beauxbatons","Hogwarts","Durmstrang","Ilvermorny"],answerIndex:1,explanation:"Harry Potter attends Hogwarts."},
{id:"200-fitness-amrap",category:"Fitness",difficulty:"Easy-Medium",question:"In CrossFit, what does AMRAP usually stand for?",options:["As Many Rounds/Reps As Possible","Advanced Movement Range And Power","Athlete Max Rep Attempt Plan","Active Mobility Recovery After Practice"],answerIndex:0,explanation:"AMRAP means As Many Rounds or Reps As Possible."},
{id:"200-nature-penguins",category:"Animals",difficulty:"Easy-Medium",question:"Penguins are birds, but what can’t they do?",options:["Swim","Lay eggs","Fly","Eat fish"],answerIndex:2,explanation:"Penguins are flightless birds."}
],
300:[
{id:"300-science-gold",category:"Science",difficulty:"Medium",question:"On the periodic table, what element has the symbol Au?",options:["Silver","Gold","Argon","Aluminum"],answerIndex:1,explanation:"Au is the chemical symbol for gold."},
{id:"300-history-liberty-bell",category:"History",difficulty:"Medium",question:"The Liberty Bell is located in which U.S. city?",options:["Boston","Philadelphia","Washington, D.C.","New York City"],answerIndex:1,explanation:"The Liberty Bell is in Philadelphia."},
{id:"300-books-tolkien",category:"Books",difficulty:"Medium",question:"Who wrote The Lord of the Rings?",options:["C.S. Lewis","J.R.R. Tolkien","George R.R. Martin","Robert Jordan"],answerIndex:1,explanation:"J.R.R. Tolkien wrote The Lord of the Rings."},
{id:"300-food-tiramisu",category:"Food",difficulty:"Medium",question:"Which Italian dessert uses mascarpone and espresso-soaked ladyfingers?",options:["Cannoli","Tiramisu","Gelato","Panna cotta"],answerIndex:1,explanation:"Tiramisu is made with mascarpone and coffee-soaked ladyfingers."},
{id:"300-sports-world-cup",category:"Sports",difficulty:"Medium",question:"How often is the FIFA World Cup usually held?",options:["Every 2 years","Every 3 years","Every 4 years","Every 5 years"],answerIndex:2,explanation:"The FIFA World Cup is traditionally held every four years."},
{id:"300-music-g-clef",category:"Music",difficulty:"Medium",question:"Which clef is also known as the G clef?",options:["Bass clef","Treble clef","Alto clef","Tenor clef"],answerIndex:1,explanation:"The treble clef is also called the G clef."},
{id:"300-geography-nile",category:"Geography",difficulty:"Medium",question:"The Nile River primarily flows through which continent?",options:["Asia","Africa","Europe","South America"],answerIndex:1,explanation:"The Nile River is in Africa."},
{id:"300-us-history-bill-rights",category:"U.S. History",difficulty:"Medium",question:"What are the first ten amendments to the U.S. Constitution called?",options:["The Federalist Papers","The Bill of Rights","The Articles","The Civil Clauses"],answerIndex:1,explanation:"The first ten amendments are called the Bill of Rights."}
],
400:[
{id:"400-science-mitochondria",category:"Science",difficulty:"Hard",question:"What part of the cell is often called the powerhouse of the cell?",options:["Nucleus","Ribosome","Mitochondria","Cell membrane"],answerIndex:2,explanation:"Mitochondria generate much of the energy cells use."},
{id:"400-literature-hamlet",category:"Literature",difficulty:"Hard",question:"Which Shakespeare play is set mainly in Denmark?",options:["Macbeth","Hamlet","Othello","King Lear"],answerIndex:1,explanation:"Hamlet is set mainly in Denmark."},
{id:"400-sports-perfect-game",category:"Sports",difficulty:"Hard",question:"In baseball, how many batters are retired in a perfect 9-inning game?",options:["24","25","27","30"],answerIndex:2,explanation:"A perfect game requires 27 consecutive outs."},
{id:"400-geography-ottawa",category:"Geography",difficulty:"Hard",question:"What is the capital city of Canada?",options:["Toronto","Vancouver","Montreal","Ottawa"],answerIndex:3,explanation:"Ottawa is the capital of Canada."},
{id:"400-history-seven-hills",category:"History",difficulty:"Hard",question:"Rome is famously said to have been built on how many hills?",options:["Five","Six","Seven","Eight"],answerIndex:2,explanation:"Rome is famously associated with seven hills."},
{id:"400-mythology-odyssey",category:"Mythology",difficulty:"Hard",question:"Who is the hero of Homer’s Odyssey?",options:["Achilles","Odysseus","Hector","Perseus"],answerIndex:1,explanation:"The Odyssey follows Odysseus on his journey home."},
{id:"400-tech-html",category:"Technology",difficulty:"Hard",question:"What does HTML stand for?",options:["HyperText Markup Language","High Transfer Machine Logic","Home Tool Markup List","Hyperlink Text Management Layer"],answerIndex:0,explanation:"HTML stands for HyperText Markup Language."},
{id:"400-music-allegro",category:"Music",difficulty:"Hard",question:"In music, what does allegro generally mean?",options:["Slow","Fast or lively","Softly","With silence"],answerIndex:1,explanation:"Allegro usually indicates a fast or lively tempo."}
],
500:[
{id:"500-science-voyager",category:"Science",difficulty:"Hardest",question:"Which NASA spacecraft pair launched in 1977 to study the outer planets?",options:["Pioneer 1 and 2","Voyager 1 and 2","Mariner 5 and 6","Apollo 10 and 11"],answerIndex:1,explanation:"Voyager 1 and Voyager 2 launched in 1977 and studied the outer planets."},
{id:"500-history-magna-carta",category:"History",difficulty:"Hardest",question:"The Magna Carta was signed in which year?",options:["1066","1215","1492","1776"],answerIndex:1,explanation:"King John agreed to the Magna Carta in 1215."},
{id:"500-literature-1984",category:"Literature",difficulty:"Hardest",question:"Who wrote the novel 1984?",options:["Aldous Huxley","George Orwell","Ray Bradbury","Kurt Vonnegut"],answerIndex:1,explanation:"George Orwell wrote 1984."},
{id:"500-art-starry-night",category:"Art",difficulty:"Hardest",question:"Who painted The Starry Night?",options:["Claude Monet","Pablo Picasso","Vincent van Gogh","Salvador Dalí"],answerIndex:2,explanation:"Vincent van Gogh painted The Starry Night."},
{id:"500-math-prime",category:"Math",difficulty:"Hardest",question:"Which of these numbers is prime?",options:["21","33","37","49"],answerIndex:2,explanation:"37 is prime because it has no positive divisors other than 1 and itself."},
{id:"500-bible-damascus",category:"Bible",difficulty:"Hardest",question:"On the road to which city did Saul experience the event tied to his conversion?",options:["Jerusalem","Damascus","Rome","Antioch"],answerIndex:1,explanation:"Saul’s conversion is traditionally associated with the road to Damascus."},
{id:"500-tech-eniac",category:"Technology",difficulty:"Hardest",question:"ENIAC is commonly associated with the early history of what?",options:["Television","Computers","Satellites","Radio"],answerIndex:1,explanation:"ENIAC was an early electronic general-purpose computer."},
{id:"500-geography-istanbul",category:"Geography",difficulty:"Hardest",question:"Which city is famously located on two continents?",options:["Athens","Istanbul","Cairo","Lisbon"],answerIndex:1,explanation:"Istanbul spans Europe and Asia across the Bosporus."}
]
};
const FINAL_BANK=[
{id:"final-africa",category:"World Geography",question:"Which continent has the most countries?",options:["Africa","Asia","Europe","South America"],answerIndex:0,explanation:"Africa has the most internationally recognized countries of any continent."},
{id:"final-adams",category:"U.S. History",question:"Who was the first U.S. president to live in the White House?",options:["George Washington","John Adams","Thomas Jefferson","James Madison"],answerIndex:1,explanation:"John Adams was the first president to live in the White House."},
{id:"final-nitrogen",category:"Science",question:"Which element is most abundant in Earth’s atmosphere?",options:["Oxygen","Nitrogen","Carbon","Hydrogen"],answerIndex:1,explanation:"Nitrogen makes up most of Earth’s atmosphere."},
{id:"final-smaug",category:"Books",question:"In The Hobbit, what is the name of the dragon?",options:["Smaug","Glaurung","Drogon","Ancalagon"],answerIndex:0,explanation:"Smaug is the dragon in The Hobbit."},
{id:"final-mound",category:"Sports",question:"In Major League Baseball, the pitching rubber is how far from home plate?",options:["55 feet","60 feet 6 inches","63 feet","66 feet 6 inches"],answerIndex:1,explanation:"The MLB pitching rubber is 60 feet 6 inches from home plate."},
{id:"final-abbey-road",category:"Music",question:"Which Beatles album features the song Come Together?",options:["Revolver","Abbey Road","Rubber Soul","Let It Be"],answerIndex:1,explanation:"Come Together appears on Abbey Road."}
];
const state={players:[],activePlayerId:null,results:{},game:null,timerId:null};
const app=document.getElementById("app"),toast=document.getElementById("toast");
function init(){state.players=loadJSON(STORAGE_KEYS.players,DEFAULT_PLAYERS);state.activePlayerId=localStorage.getItem(STORAGE_KEYS.activePlayer)||"ian";state.results=loadJSON(STORAGE_KEYS.results,{});for(const p of DEFAULT_PLAYERS){if(!state.players.some(x=>x.id===p.id))state.players.push(p)}if(!state.players.some(p=>p.id===state.activePlayerId))state.activePlayerId=state.players[0]?.id||"ian";persistPlayers();renderHome()}
function cloneFallback(x){return JSON.parse(JSON.stringify(x))}
function loadJSON(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):cloneFallback(f)}catch{return cloneFallback(f)}}
function saveJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}function persistPlayers(){saveJSON(STORAGE_KEYS.players,state.players);localStorage.setItem(STORAGE_KEYS.activePlayer,state.activePlayerId)}function persistResults(){saveJSON(STORAGE_KEYS.results,state.results)}
function activePlayer(){return state.players.find(p=>p.id===state.activePlayerId)}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function formatDateLabel(k){const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}
function money(v){return `$${Number(v||0).toLocaleString()}`}
function hashString(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)}
function pickDailyQuestion(value,dateKey,usedCategories){
  const bank=QUESTION_BANK[value]||[];
  const seed=hashString(`${dateKey}-${value}-random-category-board`);
  const shuffled=[...bank].sort((a,b)=>{
    const ah=hashString(`${dateKey}-${value}-${a.id}`),bh=hashString(`${dateKey}-${value}-${b.id}`);
    return ah-bh;
  });
  const preferred=shuffled.find(q=>!usedCategories.has(q.category))||shuffled[seed%shuffled.length];
  usedCategories.add(preferred.category);
  return{...preferred,value};
}
function dailySet(dateKey=todayKey()){
  const usedCategories=new Set();
  return{
    dateKey,
    questions:QUESTION_VALUES.map(value=>pickDailyQuestion(value,dateKey,usedCategories)),
    final:(()=>{const idx=hashString(`${dateKey}-final-ladder-v4`)%FINAL_BANK.length;return FINAL_BANK[idx]})()
  }
}
function playerResult(dateKey,playerId){return state.results?.[dateKey]?.[playerId]||null}
function renderHome(){clearTimer();state.game=null;const existing=playerResult(todayKey(),state.activePlayerId);app.innerHTML=`<section class="screen"><div class="card home-card"><div class="logo">$</div><span class="eyebrow">${formatDateLabel(todayKey())}</span><h1>Today’s Board Is Live</h1><p class="subtext">Choose player, start today’s round, and see who owns the board.</p><div class="player-picker">${state.players.map(p=>`<button class="player-option ${p.id===state.activePlayerId?"active":""}" data-player-id="${p.id}" type="button">${escapeHTML(p.name)}</button>`).join("")}</div><div class="home-actions"><button class="primary-btn" id="startRoundButton" type="button">${existing?"View Today’s Result":"Start Today’s Round"}</button><button class="secondary-btn" id="leaderboardButton" type="button">Leaderboard</button></div></div></section>`;document.querySelectorAll(".player-option").forEach(b=>b.addEventListener("click",()=>{state.activePlayerId=b.dataset.playerId;persistPlayers();renderHome()}));document.getElementById("startRoundButton").addEventListener("click",()=>{const r=playerResult(todayKey(),state.activePlayerId);r?renderResults(r):startGame()});document.getElementById("leaderboardButton").addEventListener("click",renderLeaderboard)}
function startGame(){const set=dailySet(),p=activePlayer();if(!p)return renderHome();const existing=playerResult(set.dateKey,p.id);if(existing)return renderResults(existing);state.game={playerId:p.id,playerName:p.name,dateKey:set.dateKey,questions:set.questions,final:set.final,currentIndex:0,bank:0,answers:[],selectedIndex:null,phase:"question",locked:false,completed:false,timeLeft:QUESTION_SECONDS};renderQuestion()}
function renderQuestion(){clearTimer();const g=state.game,q=g.questions[g.currentIndex];g.selectedIndex=null;g.locked=false;g.phase="question";g.timeLeft=QUESTION_SECONDS;app.innerHTML=`<section class="screen"><div class="game-header"><div class="header-left"><span class="round-label">Q${g.currentIndex+1} · ${escapeHTML(q.category)} · ${escapeHTML(q.difficulty||"")} · ${money(q.value)}</span><span class="bank-label">${escapeHTML(g.playerName)} · Bank ${money(g.bank)}</span></div><div class="timer" id="timer">${g.timeLeft}</div></div><div class="card game-card"><span class="clue-value">For ${money(q.value)}</span><div class="clue-text">${escapeHTML(q.question)}</div><div class="answer-grid">${q.options.map((o,i)=>`<button class="answer-option" data-answer-index="${i}" type="button">${escapeHTML(o)}</button>`).join("")}</div><div class="submit-area"><button class="primary-btn" id="submitAnswerButton" type="button" disabled>Submit</button></div></div></section>`;document.querySelectorAll(".answer-option").forEach(b=>b.addEventListener("click",()=>{if(g.locked)return;g.selectedIndex=Number(b.dataset.answerIndex);document.querySelectorAll(".answer-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.getElementById("submitAnswerButton").disabled=false}));document.getElementById("submitAnswerButton").addEventListener("click",()=>submitQuestionAnswer(g.selectedIndex,"answer"));startTimer(()=>submitQuestionAnswer(null,"time"))}
function submitQuestionAnswer(selectedIndex,reason="answer"){const g=state.game;if(!g||g.locked)return;g.locked=true;clearTimer();const q=g.questions[g.currentIndex],correct=selectedIndex===q.answerIndex,earned=correct?q.value:0;g.bank+=earned;const answer={questionId:q.id,category:q.category,value:q.value,selectedIndex,correct,earned,reason};g.answers.push(answer);renderQuestionFeedback(q,answer)}
function renderQuestionFeedback(q,a){const g=state.game,isLast=g.currentIndex+1>=g.questions.length,title=a.correct?"Correct!":a.reason==="time"?"Time!":a.reason==="tab"?"Forfeit!":"Incorrect",subtitle=a.correct?`You won ${money(a.earned)}.`:"You won $0.";app.innerHTML=`<section class="screen"><div class="game-header"><div class="header-left"><span class="round-label">Q${g.currentIndex+1} Result</span><span class="bank-label">Current Bank ${money(g.bank)}</span></div></div><div class="card game-card"><div class="feedback-card"><span class="feedback-title ${a.correct?"good":"bad"}">${title}</span><span class="feedback-money">${subtitle}</span><p class="feedback-explanation">${escapeHTML(q.explanation)}</p><button class="primary-btn" id="nextButton" type="button">${isLast?"Go to Final Ladder":"Next Clue"}</button></div></div></section>`;document.getElementById("nextButton").addEventListener("click",()=>{if(isLast)renderFinalSetup();else{g.currentIndex+=1;renderQuestion()}})}
function renderFinalSetup(){clearTimer();const g=state.game;app.innerHTML=`<section class="screen"><div class="card final-card"><span class="eyebrow">Final Ladder</span><h2>Make Your Wager</h2><p class="subtext">Current Bank: ${money(g.bank)}. Correct adds your wager. Incorrect subtracts it.</p><div class="wager-options"><input class="text-input" id="wagerInput" type="number" min="0" max="${g.bank}" step="100" value="${Math.min(500,g.bank)}"/><div class="row-actions"><button class="secondary-btn" data-wager="0" type="button">${money(0)}</button><button class="secondary-btn" data-wager="${Math.floor(g.bank/2)}" type="button">Half</button><button class="secondary-btn" data-wager="${g.bank}" type="button">All In</button></div></div><div class="row-actions"><button class="primary-btn" id="lockWagerButton" type="button">Lock Wager</button><button class="secondary-btn" id="skipFinalButton" type="button">Skip Final</button></div></div></section>`;document.querySelectorAll("[data-wager]").forEach(b=>b.addEventListener("click",()=>document.getElementById("wagerInput").value=b.dataset.wager));document.getElementById("lockWagerButton").addEventListener("click",()=>{g.finalWager=clampWager(Number(document.getElementById("wagerInput").value||0),g.bank);renderFinalQuestion()});document.getElementById("skipFinalButton").addEventListener("click",()=>saveCompletedGame({selectedIndex:null,correct:false,wager:0,reason:"skipped",earned:0}))}
function renderFinalQuestion(){clearTimer();const g=state.game,f=g.final;g.selectedIndex=null;g.locked=false;g.phase="final";g.timeLeft=FINAL_SECONDS;app.innerHTML=`<section class="screen"><div class="game-header"><div class="header-left"><span class="round-label">Final Ladder · ${escapeHTML(f.category)}</span><span class="bank-label">Bank ${money(g.bank)} · Wager ${money(g.finalWager)}</span></div><div class="timer" id="timer">${g.timeLeft}</div></div><div class="card game-card"><span class="clue-value">Final Wager ${money(g.finalWager)}</span><div class="clue-text">${escapeHTML(f.question)}</div><div class="answer-grid">${f.options.map((o,i)=>`<button class="answer-option" data-answer-index="${i}" type="button">${escapeHTML(o)}</button>`).join("")}</div><div class="submit-area"><button class="primary-btn" id="submitFinalButton" type="button" disabled>Submit Final</button></div></div></section>`;document.querySelectorAll(".answer-option").forEach(b=>b.addEventListener("click",()=>{if(g.locked)return;g.selectedIndex=Number(b.dataset.answerIndex);document.querySelectorAll(".answer-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.getElementById("submitFinalButton").disabled=false}));document.getElementById("submitFinalButton").addEventListener("click",()=>submitFinalAnswer(g.selectedIndex,"answer"));startTimer(()=>submitFinalAnswer(null,"time"))}
function submitFinalAnswer(selectedIndex,reason="answer"){const g=state.game;if(!g||g.locked)return;g.locked=true;clearTimer();const f=g.final,correct=selectedIndex===f.answerIndex,earned=correct?g.finalWager:-g.finalWager,finalBank=Math.max(0,g.bank+earned);renderFinalFeedback(f,{selectedIndex,correct,wager:g.finalWager,reason,earned,finalBank})}
function renderFinalFeedback(f,a){const title=a.correct?"Correct!":a.reason==="time"?"Time!":a.reason==="tab"?"Forfeit!":"Incorrect",moneyText=a.correct?`You added ${money(a.wager)}.`:`You lost ${money(a.wager)}.`;app.innerHTML=`<section class="screen"><div class="card game-card"><div class="feedback-card"><span class="feedback-title ${a.correct?"good":"bad"}">${title}</span><span class="feedback-money">${moneyText}</span><p class="feedback-explanation">${escapeHTML(f.explanation)}</p><button class="primary-btn" id="saveResultButton" type="button">Save Result</button></div></div></section>`;document.getElementById("saveResultButton").addEventListener("click",()=>saveCompletedGame(a))}
function saveCompletedGame(finalAnswer){const g=state.game,bank=typeof finalAnswer.finalBank==="number"?finalAnswer.finalBank:Math.max(0,g.bank+(finalAnswer.earned||0));const result={playerId:g.playerId,playerName:g.playerName,dateKey:g.dateKey,bank,completedAt:new Date().toISOString(),answers:g.answers,final:{questionId:g.final.id,category:g.final.category,wager:finalAnswer.wager||0,selectedIndex:finalAnswer.selectedIndex,correct:finalAnswer.correct,reason:finalAnswer.reason,earned:finalAnswer.earned||0}};if(!state.results[g.dateKey])state.results[g.dateKey]={};state.results[g.dateKey][g.playerId]=result;persistResults();state.game=null;showToast("Result saved.");renderResults(result)}
function renderResults(result){clearTimer();const stats=computeStats(),s=stats[result.playerId]||{record:{w:0,d:0,l:0},streak:"—",lifetimeBank:result.bank};app.innerHTML=`<section class="screen"><div class="card results-card"><span class="eyebrow">${formatDateLabel(result.dateKey)}</span><h2>${escapeHTML(result.playerName)}’s Final Bank</h2><div class="big-money">${money(result.bank)}</div><div class="stat-grid"><div class="stat-card"><span>Overall Record</span><strong>${s.record.w}-${s.record.d}-${s.record.l}</strong></div><div class="stat-card"><span>Current Streak</span><strong>${s.streak}</strong></div><div class="stat-card"><span>Lifetime Bank</span><strong>${money(s.lifetimeBank)}</strong></div></div><div class="share-card"><h3>Playing on separate phones?</h3><p class="small-muted">Copy this score code and text it over. The other phone can import it on the leaderboard.</p><textarea class="score-code" id="scoreCodeBox" readonly>${encodeScoreCode(result)}</textarea><button class="primary-btn" id="copyScoreCodeButton" type="button">Copy Score Code</button></div><div class="row-actions"><button class="primary-btn" id="leaderboardButton" type="button">Leaderboard</button><button class="secondary-btn" id="homeButton" type="button">Home</button><button class="danger-btn" id="resetTodayButton" type="button">Reset Today</button></div></div></section>`;document.getElementById("copyScoreCodeButton").addEventListener("click",async()=>{await copyTextToClipboard(document.getElementById("scoreCodeBox").value);showToast("Score code copied.")});document.getElementById("leaderboardButton").addEventListener("click",renderLeaderboard);document.getElementById("homeButton").addEventListener("click",renderHome);document.getElementById("resetTodayButton").addEventListener("click",()=>{if(state.results[todayKey()]?.[result.playerId]){delete state.results[todayKey()][result.playerId];persistResults();showToast("Today’s score reset.");renderHome()}})}
function renderLeaderboard(){clearTimer();const stats=computeStats(),sorted=Object.values(stats).sort((a,b)=>{const t=(b.todayBank??-1)-(a.todayBank??-1);return t!==0?t:b.lifetimeBank-a.lifetimeBank});const rows=sorted.map(s=>`<tr><td><strong>${escapeHTML(s.player.name)}</strong></td><td class="money-cell">${s.todayBank===null?"—":money(s.todayBank)}</td><td>${s.record.w}-${s.record.d}-${s.record.l}</td><td>${s.streak}</td><td>${s.winsThisWeek}</td><td>${s.overallWins}</td><td class="money-cell">${money(s.lifetimeBank)}</td></tr>`).join("");app.innerHTML=`<section class="screen"><div class="card leaderboard-card"><span class="eyebrow">${formatDateLabel(todayKey())}</span><h2>Leaderboard</h2><div class="table-wrap"><table><thead><tr><th>Player</th><th>Today</th><th>Record</th><th>Streak</th><th>Week Wins</th><th>Total Wins</th><th>Lifetime</th></tr></thead><tbody>${rows}</tbody></table></div><div class="import-card"><h3>Import Score Code</h3><p class="small-muted">Paste the score code from the other phone to update this leaderboard.</p><textarea class="score-code" id="importScoreCodeBox" placeholder="Paste score code here"></textarea><button class="primary-btn" id="importScoreButton" type="button">Import Score</button></div><div class="row-actions"><button class="primary-btn" id="homeButton" type="button">Home</button><button class="danger-btn" id="clearDataButton" type="button">Clear Saved Data</button></div></div></section>`;document.getElementById("homeButton").addEventListener("click",renderHome);document.getElementById("importScoreButton").addEventListener("click",()=>{const code=document.getElementById("importScoreCodeBox").value.trim();if(!code)return showToast("Paste a score code first.");try{const imported=importScoreCode(code);showToast(`${imported.playerName}'s ${money(imported.bank)} score imported.`);renderLeaderboard()}catch{showToast("That score code did not work.")}});document.getElementById("clearDataButton").addEventListener("click",()=>{if(!window.confirm("Clear all saved scores from this browser?"))return;localStorage.removeItem(STORAGE_KEYS.results);state.results={};showToast("Scores cleared.");renderLeaderboard()})}
function computeStats(){const stats={},playerIds=state.players.map(p=>p.id);for(const player of state.players)stats[player.id]={player,todayBank:playerResult(todayKey(),player.id)?.bank??null,lifetimeBank:0,overallWins:0,winsThisWeek:0,record:{w:0,d:0,l:0},streak:"—"};for(const [dateKey,byPlayer] of Object.entries(state.results||{}))for(const [playerId,result] of Object.entries(byPlayer||{}))if(stats[playerId])stats[playerId].lifetimeBank+=result.bank||0;const dates=Object.keys(state.results||{}).sort(),weekStart=getWeekStart();for(const dateKey of dates){const byPlayer=state.results[dateKey]||{},completed=playerIds.map(id=>({id,result:byPlayer[id]})).filter(x=>x.result);if(completed.length<2)continue;const high=Math.max(...completed.map(x=>x.result.bank)),winners=completed.filter(x=>x.result.bank===high),isThisWeek=keyToDate(dateKey)>=weekStart;for(const item of completed){if(winners.length>1)stats[item.id].record.d+=1;else if(winners[0].id===item.id){stats[item.id].record.w+=1;stats[item.id].overallWins+=1;if(isThisWeek)stats[item.id].winsThisWeek+=1}else stats[item.id].record.l+=1}}for(const id of playerIds)stats[id].streak=computeCurrentStreak(id,dates);return stats}
function computeCurrentStreak(playerId,dates){const playerIds=state.players.map(p=>p.id);let type=null,count=0;for(let i=dates.length-1;i>=0;i--){const byPlayer=state.results[dates[i]]||{},completed=playerIds.map(id=>({id,result:byPlayer[id]})).filter(x=>x.result);if(completed.length<2||!byPlayer[playerId])continue;const high=Math.max(...completed.map(x=>x.result.bank)),winners=completed.filter(x=>x.result.bank===high),dayType=winners.length>1?"D":winners[0].id===playerId?"W":"L";if(!type){type=dayType;count=1}else if(type===dayType)count+=1;else break}return type?`${type}${count}`:"—"}
function getWeekStart(date=new Date()){const d=new Date(date),day=d.getDay(),diff=day===0?-6:1-day;d.setDate(d.getDate()+diff);d.setHours(0,0,0,0);return d}function keyToDate(k){const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d)}
function startTimer(onExpire){clearTimer();state.timerId=setInterval(()=>{if(!state.game||state.game.locked)return;state.game.timeLeft-=1;const timer=document.getElementById("timer");if(timer){timer.textContent=Math.max(state.game.timeLeft,0);timer.classList.toggle("warning",state.game.timeLeft<=10)}if(state.game.timeLeft<=0)onExpire()},1000)}function clearTimer(){if(state.timerId)clearInterval(state.timerId);state.timerId=null}
document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.game&&!state.game.locked){state.game.phase==="final"?submitFinalAnswer(null,"tab"):submitQuestionAnswer(null,"tab")}});
function clampWager(wager,bank){if(!Number.isFinite(wager))return 0;return Math.max(0,Math.min(bank,Math.round(wager)))}
function encodeScoreCode(result){const safe={app:"trivia-ladder",version:4,dateKey:result.dateKey,playerName:result.playerName,bank:result.bank,completedAt:result.completedAt,answers:result.answers||[],final:result.final||{}};return btoa(unescape(encodeURIComponent(JSON.stringify(safe))))}
function decodeScoreCode(code){const json=decodeURIComponent(escape(atob(String(code||"").trim()))),payload=JSON.parse(json);if(payload.app!=="trivia-ladder"||!payload.dateKey||!payload.playerName||typeof payload.bank!=="number")throw new Error("Invalid score code");return payload}
function importScoreCode(code){const payload=decodeScoreCode(code),name=String(payload.playerName||"Player").trim();let player=state.players.find(p=>p.name.toLowerCase()===name.toLowerCase());if(!player){player={id:makeSafePlayerIdFromName(name),name,createdAt:new Date().toISOString(),imported:true};state.players.push(player);persistPlayers()}const result={...payload,playerId:player.id,playerName:player.name,importedAt:new Date().toISOString()};if(!state.results[payload.dateKey])state.results[payload.dateKey]={};state.results[payload.dateKey][player.id]=result;persistResults();return result}
function makeSafePlayerIdFromName(name){const clean=String(name||"Player").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");return clean||`player_${Date.now()}`}async function copyTextToClipboard(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);const ta=document.createElement("textarea");ta.value=text;ta.style.position="fixed";ta.style.left="-9999px";document.body.appendChild(ta);ta.focus();ta.select();document.execCommand("copy");ta.remove()}
function showToast(message){toast.textContent=message;toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),2300)}
function escapeHTML(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
init();
